### PR TITLE
Proposing `hasTouch` prop

### PR DESCRIPTION
**Pull request by irfaan**
Tells us when the ScrollableTabView is starts being moved and when it is released. Useful?

### CODE REVIEW

**Comment by brentvatne** [comment]
@irfaan - could be useful, what's your particular use case for it?

**Comment by irfaan** [comment]
Dismiss keyboard when switching to another view. I didn't want to wait until the next view was reached.

**Comment by brentvatne** [comment]
Makes sense, let's do it

**Comment by brentvatne** [comment]
Published in 0.1.10

**Pull request merged**
