### PR TITLE
Switch to ScrollView

### PR DESCRIPTION
**Pull request by devknoll**
This builds on my Animated.js TabBar PR to make the scrollable tab view use a ScrollView, since that already supports paging. As a bonus, the code gets a little shorter too.

### CODE REVIEW

**Comment by brentvatne** [comment]
Oh awesome I will definitely check this out tonight. I originally didn't use the ScrollView's paging functionality because I wanted to have full control over the scroll behaviour. Gotta get this newsletter out first though :D

**Comment by devknoll** [comment]
For `edgeHitWidth`? I guess that makes sense. I wonder how many iOS apps just use ScrollView though :smile:

**Comment by syarul** [comment]
+1 PR this solve issue on Android, panResponder does not work and only allow the first page working. issue #62, #58

**Comment by devknoll** [comment]
@syarul doesn't android have this control natively? Would it be better to just use that one there? :wink:

**Comment by syarul** [comment]
@devknoll I was looking for quick solution, I look through the code which kinda the problem in which I'm having is related to panResponder not working on Android, Well for your question, I guess it does but this repo does give a neat solution to handle scrollable tabs out of the box for react-native Android with bare minimum editing the source code. Thanks, glad it work!

**Comment by chirag04** [comment]
+1

**Comment by brentvatne** [comment]
Done in another commit now :) Using ViewPager on Android and ScrollView on iOS. Thanks @devknoll

**Pull request closed without merging**
