### PR TITLE
examples/FacebookTabsExample: Align the icons to the center.

### PR DESCRIPTION
**Pull request by jeffjose**
Currently the FacebookTabBar examples looks wonky in landscape mode. I took a stab at fixing it by using flexbox for the parent container of the icons. This is my first react-native PR, so please be kind.

Cheers!
Jeff

### CODE REVIEW

**Comment by skv-headless** [comment]
@jeffjose thanks for interest to project :+1: . During scroll there is animation of changing color. In your solution it might be lost.

**Comment by skv-headless** [comment]
https://github.com/brentvatne/react-native-scrollable-tab-view/blob/master/examples/FacebookTabsExample/FacebookTabBar.js#L68 here how it works.

**Comment by danielpeiro** [comment]
thanks jeffjose

**Comment by skv-headless** [comment]
fixed here https://github.com/brentvatne/react-native-scrollable-tab-view/commit/f70227081bca069a412f4e53cde45843192cbf2e

**Pull request closed without merging**
