### PR TITLE
update example deps, android version

### PR DESCRIPTION
**Pull request by skv-headless**
I want to make patch, but I wasn't able to launch examples, I think because of watchman.

### CODE REVIEW

**Comment by skv-headless** [comment]
first commit - update FacebookTabsExample 
second commit - move from Animated.View to ScrollView for ios
@brentvatne if you interested I'll make android implementation for Android with ViewPager

Why I did this:
https://github.com/brentvatne/react-native-scrollable-tab-view/pull/79
here content overlaps my side menu and I can't tap on any of menu items.

**Comment by brentvatne** [comment]
Hey @skv-headless thank you so much! I'll review this some time today and get back to you, sorry for the delay!

**Comment by allenmanning** [comment]
> if you interested I'll make android implementation for Android with ViewPager
+1

**Comment by brentvatne** [comment]
Sorry for the delay, today I promise :angel: :innocent:

**Comment by skv-headless** [comment]
I've already switched to my implementation. So I don't hurry. 
If you won't merge it I can create separate package.

**Pull request merged**
