### PR TITLE
Add 'scrollEnabled' prop to ScrollableTabView + corresponding readme entry

### PR DESCRIPTION
**Pull request by irfaan**

### CODE REVIEW

**Comment by irfaan** [comment]
Or perhaps it should be named something other than 'scroll'?

**Comment by brentvatne** [comment]
Maybe "locked"? @irfaan

**Comment by irfaan** [comment]
Changed.

**Comment by brentvatne** [comment]
Sounds good, thanks @irfaan!

**Comment by brentvatne** [comment]
I'll cut a release for this sometime next week, for now you can point to master from npm if you need to use this

**Pull request merged**
